spring:
  application:
    name: Spring-React

  datasource:
    url: jdbc:mysql://localhost:3306/spring_react
    username: root
    password: root1234

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

    open-in-view: false